include ../../Makefile.param
include ../Makefile.param



TARGET      = hkipc_noOnvif
OBJPATH     = .
SOURCES     = $(wildcard *.c) 
OBJS        = $(patsubst %.c,%.o,$(SOURCES))
FULLOBJS    = $(patsubst %.c,$(OBJPATH)/%.o,$(SOURCES))
TARGETPATH  = /tftpboot/zqjun/3518e

INCPATH     = -I . -I /home/luozhi/system/include 			  \
			  -I ../../include 								  \
			  -I /lodb3/Hi3518_SDK_V1.0.8.1/mpp/extdrv/tw2865 \
			  -I /home/zqjun/openssl_3518/lib_openssl/include \
			  -I /lodb3/Hi3518_SDK_V1.0.8.1/drv/hisi-irda	  \
			  -I /home/wss/wss_hi3518e_web/include

LIBPATH     = -L ../lib_so -lsystem -lchinalink -lnetfactory -lutils 									\
			  -L ../../lib -lpthread -lm -lmpi -lVoiceEngine -laec -lresampler -lanr -lisp -lsns_ov9712 \
			  -L /home/zqjun/openssl_3518/lib_openssl/lib -lssl -lcrypto
			
WEB_MODULES=/home/wss/wss_hi3518e_web/lib/MOD_NetServer.a	\
		/home/wss/wss_hi3518e_web/lib/Mod_NetConfig.a	\
		/home/wss/wss_hi3518e_web/lib/MOD_NetWebCallBack.a \
		/home/wss/wss_hi3518e_web/lib/MOD_NetSvStreamVideo.a \
		/home/wss/wss_hi3518e_web/lib/MOD_NetSvStreamAudio.a \
		/home/wss/wss_hi3518e_web/lib/MOD_NetClStreamAudio.a \
		/home/wss/wss_hi3518e_web/lib/MOD_NetDdns.a \
		/home/wss/wss_hi3518e_web/lib/LIB_Ddns.a \
		/home/wss/wss_hi3518e_web/lib/MOD_SysContext.a	\
		/home/wss/wss_hi3518e_web/lib/MOD_Cgi.a	\
		/home/wss/wss_hi3518e_web/lib/MOD_MulLanguage.a	\
		/home/wss/wss_hi3518e_web/lib/LIB_WebServer.a\
		/lodb3/Hi3518C_SDK_V1.0.8.1/mpp/sample/lib_so/libvoiceADC.a


ONVIF_MODULES=/home/wss/wss_hi3518e_web/lib/MOD_NetSvRtsp.a \
			/home/wss/wss_hi3518e_web/lib/MOD_OnvifServer.a

##
## MODULES = /home/wss/wss_hi3518e_web/lib/MOD_NetSvRtsp.a \
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_NetServer.a	\
## 		   		/home/wss/wss_hi3518e_web/lib/Mod_NetConfig.a	\
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_NetWebCallBack.a \
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_NetSvStreamVideo.a \
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_NetSvStreamAudio.a \
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_NetClStreamAudio.a \
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_NetDdns.a \
## 		   		/home/wss/wss_hi3518e_web/lib/LIB_Ddns.a \
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_SysContext.a	\
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_Cgi.a	\
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_MulLanguage.a	\
## 		   		/home/wss/wss_hi3518e_web/lib/LIB_WebServer.a	\
## 		   		/home/wss/wss_hi3518e_web/lib/MOD_OnvifServer.a						
## 

LINKFLAGS   = -Wall -g
COMPFLAGS   = -c -O2 -fPIC -lpthread -D_GNU_SOURCE -D_HKIPC -DRTSARM
CXX         = arm-hisiv100nptl-linux-gcc


all:$(TARGET)

$(TARGET):$(OBJS)
	$(CXX) $(LINKFLAGS) $(FULLOBJS) -o $(TARGET) $(LIBPATH) $(WEB_MODULES) 
	arm-hisiv100nptl-linux-strip $(TARGET)
	rm -f $(OBJPATH)/.*.swp
	rm -f $(OBJPATH)/*.o
	ls -lh $(TARGET)
	cp $(TARGET) $(TARGETPATH)/

$(OBJS):$(SOURCES)
	$(CXX) $(COMPFLAGS) $*.c -o $(OBJPATH)/$@ $(INCPATH) 

clr:
	rm -f $(OBJPATH)/*.o
	ctags -Rn ./

clean:
	rm -f $(OBJPATH)/*.o
	rm -f $(OBJPATH)/.*.swp
	rm -f $(TARGET)
	rm -f $(TARGETPATH)/$(TARGET)
	ctags -Rn ./* ../../include/* /home/luozhi/system/include /lodb3/Hi3518_SDK_V1.0.8.1/mpp/component/isp/sensor/ov_9712+ .

